In [10]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import sys
from pathlib import Path

ROOT = Path.cwd().parent
sys.path.append(str(ROOT))
from src.config import RAW_DATA_PATH

In [11]:
df = pd.read_csv(RAW_DATA_PATH)

In [13]:
df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

In [25]:
df["high_debt"] = (df["loan_int_rate"] > df["loan_int_rate"].median()) & (df["loan_amnt"] > df["loan_amnt"].median()).astype(int)

In [26]:
df["high_debt"] = df["high_debt"].astype(int)

In [ ]:
# bu feature'u kullanmayacam çünkü data leakege olacaktır.

In [34]:
df["credit_history_age_ratio"] = (df["cb_person_cred_hist_length"] / df["person_age"])

In [35]:
df

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,high_debt,credit_history_age_ratio
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3,1,0.136364
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2,0,0.095238
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3,0,0.120000
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2,1,0.086957
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4,1,0.166667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32576,57,53000,MORTGAGE,1.0,PERSONAL,C,5800,13.16,0,0.11,N,30,0,0.526316
32577,54,120000,MORTGAGE,4.0,PERSONAL,A,17625,7.49,0,0.15,N,19,0,0.351852
32578,65,76000,RENT,3.0,HOMEIMPROVEMENT,B,35000,10.99,1,0.46,N,28,0,0.430769
32579,56,150000,MORTGAGE,5.0,PERSONAL,B,15000,11.48,0,0.10,N,26,1,0.464286
32580,66,42000,RENT,2.0,MEDICAL,B,6475,9.99,0,0.15,N,30,0,0.454545

In [39]:
df.sort_values(by="person_age").head(20)

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,high_debt,credit_history_age_ratio
7748,20,34800,RENT,3.0,MEDICAL,C,7000,13.61,0,0.20,Y,2,0,0.100000
1313,20,64000,RENT,3.0,VENTURE,D,16000,15.31,1,0.25,Y,4,1,0.200000
16339,20,188004,MORTGAGE,4.0,PERSONAL,A,2000,8.59,0,0.01,N,2,0,0.100000
9926,20,65000,MORTGAGE,4.0,EDUCATION,B,4800,9.99,0,0.07,N,2,0,0.100000
15830,20,188004,MORTGAGE,4.0,EDUCATION,A,2000,8.59,0,0.01,N,4,0,0.200000
7327,20,42000,RENT,4.0,VENTURE,B,6500,11.71,0,0.15,N,2,0,0.100000
15417,20,135000,MORTGAGE,1.0,VENTURE,C,15000,15.96,0,0.11,Y,2,1,0.100000
14827,20,115731,MORTGAGE,4.0,DEBTCONSOLIDATION,B,9625,10.74,0,0.08,N,3,0,0.150000
17196,20,65000,MORTGAGE,4.0,VENTURE,B,4800,9.99,0,0.07,N,4,0,0.200000
13918,20,98000,MORTGAGE,4.0,EDUCATION,D,24250,NaN,0,0.25,N,4,0,0.200000
3851,20,32652,MORTGAGE,0.0,PERSONAL,D,6000,14.61,1,0.18,N,4,0,0.200000
5648,20,94000,RENT,4.0,EDUCATION,D,5000,16.02,0,0.05,N,3,0,0.150000
11889,20,77000,MORTGAGE,4.0,VENTURE,A,6000,8.00,0,0.08,N,2,0,0.100000
11902,20,77052,MORTGAGE,4.0,EDUCATION,B,24250,11.36,0,0.31,N,2,1,0.100000
12943,20,85920,MORTGAGE,3.0,DEBTCONSOLIDATION,A,12000,8.49,0,0.14,N,2,0,0.100000
1325,21,20000,RENT,2.0,DEBTCONSOLIDATION,C,1000,14.26,0,0.05,Y,2,0,0.095238
1351,21,30000,RENT,0.0,EDUCATION,B,1000,10.99,0,0.03,N,4,0,0.190476
16458,21,60000,RENT,2.0,VENTURE,A,5000,8.49,0,0.08,N,2,0,0.095238
1339,21,26000,MORTGAGE,5.0,MEDICAL,D,14500,14.61,1,0.56,Y,2,1,0.095238
1335,21,24960,RENT,0.0,EDUCATION,C,1000,13.98,0,0.04,N,4,0,0.190476